on: push
name: Linters on push

jobs:
  lint-scala:
    name: Run scalafmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: openlawteam/scalafmt-ci@v2
