on: push
name: Linters on push

jobs:

  lint-shell:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Shellcheck Lint
      uses: actions/bin/shellcheck@master
      with:
        args: scripts/*.sh ci/*.sh