
on: release
name: Publish on Release

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # all of the below are duplicative of build.yml, and documented there.
      # TODO(mroth): do we really need this here anymore? or in new setup can
      # we move this into a gated part of build perhaps? 
    - uses: actions/checkout@v1
    - name: Docker Registry Login
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Caching Build
      run: sh -c "BRANCH=${GITHUB_REF##*/} ID=gh ci/build.sh"
      env:
        PUSH_CACHE: "1"

    # actual release stuffs
    - name: SemVer Tag Filterd
      uses: actions/bin/filter@master
      with:
        args: tag v*
    - name: Release
      run: scripts/release.sh
      env:
        RELEASE_TRIGGER: "false"
        BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
        BINTRAY_PASSWORD: ${{ secrets.BINTRAY_PASSWORD }}